actor_dic = {'Daniel Day-Lewis': 0, 'Leonardo DiCaprio': 1,
             'Philip Seymour Hoffman': 2, 'Jack Nicholson': 3,
             'Morgan Freeman': 4, 'Russell Crowe': 5, 'George Clooney': 6,
             'Javier Bardem': 7, 'Brad Pitt': 8, 'Christian Bale': 9,
             'Jeff Bridges': 10, 'Sean Penn': 11, 'Joaquin Phoenix': 12,
             'Heath Ledger': 13, 'Johnny Depp': 14,
             'Denzel Washington': 15, 'Tom Hanks': 16,
             'Clint Eastwood': 17, 'Geoffrey Rush': 18, 'Colin Firth': 19,
             'Viggo Mortensen': 20, 'Tom Wilkinson': 21, 'Gary Oldman': 22,
             'Bill Murray': 23, 'Don Cheadle': 24, 'Ed Harris': 25,
             'Michael Fassbender': 26, 'Michael Caine': 27,
             'Kevin Spacey': 28, 'Ben Kingsley': 29, 'Ian McKellen': 30,
             'Ralph Fiennes': 31, 'Tommy Lee Jones': 32,
             'Woody Harrelson': 33, 'Christopher Plummer': 34,
             'Robert Downey Jr.': 35, 'Ryan Gosling': 36,
             'Jeremy Renner': 37, 'Matthew McConaughey': 38,
             'Max von Sydow': 39, 'Albert Finney': 40, 'Paul Giamatti': 41,
             'Will Smith': 42, 'Tom Cruise': 43, 'Robert De Niro': 44,
             'Benicio Del Toro': 45, "Peter O'Toole": 46,
             'Robert Duvall': 47, 'Anthony Hopkins': 48,
             'Dustin Hoffman': 49, 'Al Pacino': 50, 'Alan Arkin': 51,
             'Michael Douglas': 52, 'Christopher Walken': 53,
             'Chris Cooper': 54, 'Jude Law': 55, 'Matt Damon': 56,
             'Jon Voight': 57, 'John Hurt': 58, 'Liam Neeson': 59,
             'Nicolas Cage': 60, 'William Hurt': 61, 'Edward Norton': 62,
             'Willem Dafoe': 63, 'Daniel Craig': 64, 'Christoph Waltz': 65,
             'Mark Wahlberg': 66, 'Paul Newman': 67, 'John Malkovich': 68,
             'Billy Bob Thornton': 69, 'Djimon Hounsou': 70,
             'Ethan Hawke': 71, 'Nick Nolte': 72, 'Tim Robbins': 73,
             'Robin Williams': 74, 'Kenneth Branagh': 75,
             'Josh Brolin': 76, 'Samuel L. Jackson': 77,
             'Bruce Willis': 78, 'Hugh Jackman': 79, 'Jamie Foxx': 80,
             'Adrien Brody': 81, 'Bruno Ganz': 82, 'Ulrich M�he': 83,
             'Jake Gyllenhaal': 84, 'Richard Jenkins': 85,
             'Frank Langella': 86, 'David Strathairn': 87,
             'Stanley Tucci': 88, 'Gene Hackman': 89, 'Guy Pearce': 90,
             'Robert Redford': 91, 'Donald Sutherland': 92,
             'Eric Bana': 93, 'Jeremy Irons': 94, 'Laurence Fishburne': 95,
             'Harrison Ford': 96, 'Ewan McGregor': 97, 'Dennis Hopper': 98,
             'G�rard Depardieu': 99, 'James Woods': 100, 'Mel Gibson': 101,
             'Richard Harris': 102, 'Martin Sheen': 103,
             'Richard Gere': 104, 'Patrick Stewart': 105,
             'Christopher Lee': 106, 'Kevin Costner': 107,
             'Terrence Howard': 108, 'Eddie Murphy': 109,
             'Pierce Brosnan': 110, 'James Franco': 111,
             'John C. Reilly': 112, 'David Carradine': 113,
             'Alec Baldwin': 114, 'Hugh Grant': 115, 'Mickey Rourke': 116,
             'Richard Dreyfuss': 117, 'James Garner': 118,
             'Harvey Keitel': 119, 'James Coburn': 120,
             'Ernest Borgnine': 121, 'Woody Allen': 122,
             'Sean Connery': 123, 'Peter Falk': 124, 'Martin Landau': 125,
             'John Travolta': 126, 'Peter Fonda': 127, 'Eli Wallach': 128,
             'Malcolm McDowell': 129, 'Jackie Earle Haley': 130,
             'Greg Kinnear': 131, 'Thomas Haden Church': 132,
             'Matt Dillon': 133, 'Casey Affleck': 134,
             'Michael Shannon': 135, 'Ken Watanabe': 136,
             'Clive Owen': 137, 'Jim Broadbent': 138, 'Bruce Davison': 139,
             'Brian Cox': 140, 'Chow Yun-Fat': 141, 'John Hawkes': 142,
             'Alan Rickman': 143, 'William H. Macy': 144,
             'Ned Beatty': 145, 'Antonio Banderas': 146,
             'Hugo Weaving': 147, 'Stephen Rea': 148,
             'Stellan Skarsg�rd': 149, 'F. Murray Abraham': 150,
             'Kevin Bacon': 151, 'John Goodman': 152, 'Scott Glenn': 153,
             'Jeff Daniels': 154, 'Jesse Eisenberg': 155, 'Sam Neill': 156,
             'Elias Koteas': 157, 'Sean Bean': 158, 'Colin Farrell': 159,
             'Jean Dujardin': 160, 'David Morse': 161,
             'Demi�n Bichir': 162, 'Forest Whitaker': 163,
             'Ray Winstone': 164, 'Michael Madsen': 165, 'Jim Carrey': 166,
             'James McAvoy': 167, 'Patrick Wilson': 168,
             'Jeffrey Wright': 169, 'Dennis Quaid': 170,
             'Sam Rockwell': 171, 'Bryan Cranston': 172,
             'Aaron Eckhart': 173, 'Chiwetel Ejiofor': 174,
             'Orlando Bloom': 175, 'Elijah Wood': 176,
             'Cillian Murphy': 177, 'Joseph Gordon-Levitt': 178,
             'Gael Garc�a Bernal': 179, 'Mark Ruffalo': 180,
             'Will Ferrell': 181, 'Sacha Baron Cohen': 182,
             'John Cusack': 183, 'Keith David': 184, 'Mads Mikkelsen': 185,
             'Jonah Hill': 186, 'Alfred Molina': 187, 'John Turturro': 188,
             'Adam Sandler': 189, 'Jack Black': 190,
             'Sylvester Stallone': 191, 'Steve Martin': 192,
             'James Earl Jones': 193, 'Michael Clarke Duncan': 194,
             'Kiefer Sutherland': 195, 'Steve Buscemi': 196,
             'Joe Pesci': 197, 'Patrick Swayze': 198,
             'Hayden Christensen': 199}

top_actor_set = {'Aaron Eckhart', 'Adam Sandler', 'Adrien Brody', 'Al Pacino',
                  'Alan Arkin', 'Alan Rickman', 'Albert Finney',
                  'Alec Baldwin', 'Alfred Molina', 'Anthony Hopkins',
                  'Antonio Banderas', 'Ben Kingsley', 'Bill Murray',
                  'Billy Bob Thornton', 'Brad Pitt', 'Brian Cox',
                  'Bruce Davison', 'Bruce Willis', 'Bruno Ganz',
                  'Bryan Cranston', 'Casey Affleck', 'Chiwetel Ejiofor',
                  'Chow Yun-Fat', 'Chris Cooper', 'Christian Bale',
                  'Christoph Waltz', 'Christopher Lee', 'Christopher Plummer',
                  'Christopher Walken', 'Cillian Murphy', 'Clint Eastwood',
                  'Clive Owen', 'Colin Farrell', 'Colin Firth', 'Daniel Craig',
                  'Daniel Day-Lewis', 'David Carradine', 'David Morse',
                  'David Strathairn', 'Dennis Hopper', 'Dennis Quaid',
                  'Denzel Washington', 'Djimon Hounsou', 'Don Cheadle',
                  'Donald Sutherland', 'Dustin Hoffman', 'Ed Harris',
                  'Eddie Murphy', 'Edward Norton', 'Eli Wallach',
                  'Elias Koteas', 'Elijah Wood', 'Eric Bana',
                  'Ernest Borgnine', 'Ethan Hawke', 'Ewan McGregor',
                  'F. Murray Abraham', 'Forest Whitaker', 'Frank Langella',
                  'Gary Oldman', 'Gene Hackman', 'Geoffrey Rush',
                  'George Clooney', 'Greg Kinnear', 'Guy Pearce',
                  'Harrison Ford', 'Harvey Keitel', 'Hayden Christensen',
                  'Heath Ledger', 'Hugh Grant', 'Hugh Jackman', 'Hugo Weaving',
                  'Ian McKellen', 'Jack Black', 'Jack Nicholson',
                  'Jackie Earle Haley', 'Jake Gyllenhaal', 'James Coburn',
                  'James Earl Jones', 'James Franco', 'James Garner',
                  'James McAvoy', 'James Woods', 'Jamie Foxx', 'Javier Bardem',
                  'Jean Dujardin', 'Jeff Bridges', 'Jeff Daniels',
                  'Jeffrey Wright', 'Jeremy Irons', 'Jeremy Renner',
                  'Jesse Eisenberg', 'Jim Broadbent', 'Jim Carrey',
                  'Joaquin Phoenix', 'Joe Pesci', 'John C. Reilly',
                  'John Cusack', 'John Goodman', 'John Hawkes', 'John Hurt',
                  'John Malkovich', 'John Travolta', 'John Turturro',
                  'Johnny Depp', 'Jon Voight', 'Jonah Hill',
                  'Joseph Gordon-Levitt', 'Josh Brolin', 'Jude Law',
                  'Keith David', 'Ken Watanabe', 'Kenneth Branagh',
                  'Kevin Bacon', 'Kevin Costner', 'Kevin Spacey',
                  'Kiefer Sutherland', 'Laurence Fishburne',
                  'Leonardo DiCaprio', 'Liam Neeson', 'Mads Mikkelsen',
                  'Malcolm McDowell', 'Mark Ruffalo', 'Mark Wahlberg',
                  'Martin Landau', 'Martin Sheen', 'Matt Damon', 'Matt Dillon',
                  'Matthew McConaughey', 'Max von Sydow', 'Mel Gibson',
                  'Michael Caine', 'Michael Clarke Duncan', 'Michael Douglas',
                  'Michael Fassbender', 'Michael Madsen', 'Michael Shannon',
                  'Mickey Rourke', 'Morgan Freeman', 'Ned Beatty',
                  'Nick Nolte', 'Nicolas Cage', 'Orlando Bloom',
                  'Patrick Stewart', 'Patrick Swayze', 'Patrick Wilson',
                  'Paul Giamatti', 'Paul Newman', 'Peter Falk', 'Peter Fonda',
                  "Peter O'Toole", 'Philip Seymour Hoffman', 'Pierce Brosnan',
                  'Ralph Fiennes', 'Ray Winstone', 'Richard Dreyfuss',
                  'Richard Gere', 'Richard Harris', 'Richard Jenkins',
                  'Robert De Niro', 'Robert Downey Jr.', 'Robert Duvall',
                  'Robert Redford', 'Robin Williams', 'Russell Crowe',
                  'Ryan Gosling', 'Sacha Baron Cohen', 'Sam Neill',
                  'Sam Rockwell', 'Samuel L. Jackson', 'Scott Glenn',
                  'Sean Bean', 'Sean Connery', 'Sean Penn', 'Stanley Tucci',
                  'Stephen Rea', 'Steve Buscemi', 'Steve Martin',
                  'Sylvester Stallone', 'Terrence Howard',
                  'Thomas Haden Church', 'Tim Robbins', 'Tom Cruise',
                  'Tom Hanks', 'Tom Wilkinson', 'Tommy Lee Jones',
                  'Viggo Mortensen', 'Will Ferrell', 'Will Smith',
                  'Willem Dafoe', 'William H. Macy', 'William Hurt',
                  'Woody Harrelson'}
